// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSData.Context;

#nullable disable

namespace PSAPI.Migrations
{
    [DbContext(typeof(ProcessContext))]
    [Migration("20220909181219_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PSDTO.ProcessDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReplayable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");
                });

            modelBuilder.Entity("PSDTO.ProcessDefinitionTaskDefinition", b =>
                {
                    b.Property<long>("ProcessDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessTaskDefinitionId")
                        .HasColumnType("bigint");

                    b.HasKey("ProcessDefinitionId", "ProcessTaskDefinitionId");

                    b.HasIndex("ProcessTaskDefinitionId");

                    b.ToTable("ProcessDefinitionTaskDefinition");
                });

            modelBuilder.Entity("PSDTO.ProcessTaskDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessTaskDefinition");
                });

            modelBuilder.Entity("PSDTO.ProcessDefinitionTaskDefinition", b =>
                {
                    b.HasOne("PSDTO.ProcessDefinition", "ProcessDefinition")
                        .WithMany("ProcessDefinitionTaskDefinitions")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSDTO.ProcessTaskDefinition", "ProcessTaskDefinition")
                        .WithMany("ProcessDefinitionTaskDefinitions")
                        .HasForeignKey("ProcessTaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessTaskDefinition");
                });

            modelBuilder.Entity("PSDTO.ProcessDefinition", b =>
                {
                    b.Navigation("ProcessDefinitionTaskDefinitions");
                });

            modelBuilder.Entity("PSDTO.ProcessTaskDefinition", b =>
                {
                    b.Navigation("ProcessDefinitionTaskDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
